server:
  port: 9092

spring:
  application:
    name: clean-arc-app
  data:
    mongodb:
      auto-index-creation: true
      database: clean-arc-example
      port: 27018
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    allow-bean-definition-overriding: true

foodtechlab:
  build:
    version: 1.0.0
  security:
    jwt:
      secret: cleanArcBackendExample1234567890
    secretWord: cleanArcBackendExample1234567890
    username: microservice
    password: cleanArcConnectPassword
  infrastructure:
    microservice:
      auth-service:
        url: http://localhost:9090
      sms:
        url: http://localhost:9091

logging:
  file:
    name: ./log.log

springdoc:
  packages-to-scan: com.campus
  paths-to-match: /api/**, /not-secure/**

springfox:
  documentation:
    enabled: false